# Change these first
owner: worklytics # Your GitHub organization or username, where this repository lives
repo: w8s-status # The name of this repository

sites:
  - name: Worklytics
    url: https://app.worklytics.co

assignees:
  - eschultink
  - jlorper

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: www.worklytics-status.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Worklytics Status
  introTitle: "This page monitors the status of the **Worklytics** web portal. "
  introMessage: Use this page to see information about downtime in the portal and any incidents affectively availability of the portal or our platform.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
